inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  AllowSymlinksInCacheRootDirectory: true
  SuggestExtensions:
    rubocop-rake: false

Metrics/AbcSize:
  Max: 16
  Exclude:
   - 'test/**/*'

Layout/LineLength:
  Max: 110
  Exclude:
   - 'test/**/*'

Lint/FloatComparison:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 13
  Exclude:
   - 'test/**/*'

Naming/MethodParameterName:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false
