inherit_from:
  - .rubocop_todo.yml

Metrics/AbcSize:
  Max: 16
  Exclude:
   - 'test/**/*'

Metrics/LineLength:
  Max: 110
  Exclude:
   - 'test/**/*'

Style/HashSyntax:
  EnforcedStyle: hash_rockets
